// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaeiycpyyjlpalyzfhiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZWl5Y3B5eWpscGFseXpmaGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzAwODYsImV4cCI6MjA2MTcwNjA4Nn0.3uVlphNhpJrvJJVrshS4EzlAOxdnCrVvB4aoiNq3V7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);